In [1]:
import os
import pandas as pd
from PIL import Image
import matplotlib.pyplot as plt
import numpy as np
import cv2
from tqdm import tqdm
import tensorflow as tf

In [2]:
base_project_folder = "./"

os.listdir(base_project_folder)

['augmented..csv',
 'augmented_df_3000_ground_truth.csv',
 'augmented_df_ground_truth.csv',
 'augmented_images',
 'augmented_images_3000',
 'augmented_new_vers',
 'backups_models',
 'ISIC2018_Task3_Test_GroundTruth.csv',
 'ISIC2018_Task3_Test_Input',
 'ISIC2018_Task3_Training_GroundTruth.csv',
 'ISIC2018_Task3_Training_Input',
 'ISIC2018_Task3_Validation_GroundTruth.csv',
 'ISIC2018_Task3_Validation_Input',
 'main.py',
 'myenv',
 'NN_training aug_also_top.ipynb',
 'NN_training.ipynb',
 'NN_training_with_rejector_mech.ipynb',
 'ordered_augmented_df.csv',
 'ordered_augmented_df_3000_unshuffeled.csv',
 'ordered_test_df.csv',
 'ordered_training_df.csv',
 'ordered_training_df_upper_limit_1500.csv',
 'ordered_training_df_upper_limit_3000.csv',
 'ordered_tranining_merged_3000.csv',
 'ordered_tranining_merged_3000.csv.zip',
 'ordered_validation_df.csv',
 'pixelated_augmented_3000.csv',
 'plain_model.h5',
 'plain_model.keras',
 'plain_model_best_perfoming.h5',
 'plain_model_with_augmentation_1000_upper_limit_1500.h5',
 'plain_model_with_augmentation_1000_upper_limit_3000.h5',
 'plain_model_with_balancing.h5',
 'plain_model_with_fin_ver.h5',
 'plain_model_with_shuffle_augmentation.h5',
 'plain_model_with_shuffle_augmentation_3000.h5',
 'preparation copy.ipynb',
 'preparation.ipynb',
 'seperation_data_by_rejection_sets_creation.ipynb',
 'test_df.csv',
 'training_df.csv',
 'training_diff_thresholds',
 'training_diff_thresholds - Copy',
 'validation_df.csv']

In [3]:
training_ground_truth = pd.read_csv(f"{base_project_folder}ISIC2018_Task3_Training_GroundTruth.csv")
validation_ground_truth = pd.read_csv(f"{base_project_folder}ISIC2018_Task3_Validation_GroundTruth.csv")
test_ground_truth = pd.read_csv(f"{base_project_folder}ISIC2018_Task3_Test_GroundTruth.csv")

training_ground_truth['image_path'] = training_ground_truth['image'].apply(lambda x: f"{base_project_folder}ISIC2018_Task3_Training_Input/{x}.jpg") 
validation_ground_truth['image_path'] = validation_ground_truth['image'].apply(lambda x: f"{base_project_folder}ISIC2018_Task3_Validation_Input/{x}.jpg") 
test_ground_truth['image_path'] = test_ground_truth['image'].apply(lambda x: f"{base_project_folder}ISIC2018_Task3_Test_Input/{x}.jpg")

print(training_ground_truth.head())

          image  MEL   NV  BCC  AKIEC  BKL   DF  VASC  \
0  ISIC_0024306  0.0  1.0  0.0    0.0  0.0  0.0   0.0
1  ISIC_0024307  0.0  1.0  0.0    0.0  0.0  0.0   0.0
2  ISIC_0024308  0.0  1.0  0.0    0.0  0.0  0.0   0.0
3  ISIC_0024309  0.0  1.0  0.0    0.0  0.0  0.0   0.0
4  ISIC_0024310  1.0  0.0  0.0    0.0  0.0  0.0   0.0

                                         image_path
0  ./ISIC2018_Task3_Training_Input/ISIC_0024306.jpg
1  ./ISIC2018_Task3_Training_Input/ISIC_0024307.jpg
2  ./ISIC2018_Task3_Training_Input/ISIC_0024308.jpg
3  ./ISIC2018_Task3_Training_Input/ISIC_0024309.jpg
4  ./ISIC2018_Task3_Training_Input/ISIC_0024310.jpg

---

In [4]:
class_distribution = training_ground_truth.drop('image', axis=1).sum(axis=0)
print(class_distribution)

MEL                                                      1113.0
NV                                                       6705.0
BCC                                                       514.0
AKIEC                                                     327.0
BKL                                                      1099.0
DF                                                        115.0
VASC                                                      142.0
image_path    ./ISIC2018_Task3_Training_Input/ISIC_0024306.j...
dtype: object

In [5]:
for index, row in minority_class_df.iterrows():
    image_path = row['image']  # Assuming you have a column 'image' with image paths
    augmented_images = augment_image(image_path, num_augmentations=5)
    
    # Get the one-hot encoded label for this class
    one_hot_label = row.drop('image').values  # The rest of the columns are one-hot encoded labels
    
    # Create augmented rows with the same one-hot encoded label
    for augmented_image in augmented_images:
        augmented_data.append({
            'image': augmented_image,  # You may want to save the image or use its raw data
            **dict(zip(training_df.columns[1:], one_hot_label))  # Add the one-hot encoded label back
        })

augmented_df = pd.DataFrame(augmented_data)

# Combine the original and augmented DataFrame
balanced_df = pd.concat([training_df, augmented_df], ignore_index=True)

print(balanced_df.drop('image', axis=1).sum(axis=0))  # Check the new class distribution

NameError: name 'minority_class_df' is not defined

---

In [5]:
def preprocess_image_rgn(image_path, target_size=(224, 224)):
    try:
        image = tf.io.read_file(image_path)
        image = tf.image.decode_jpeg(image, channels=3)
        image = tf.image.resize(image, target_size)
        image = image / 255.0
        image = tf.cast(image * 255, tf.uint8)
        return image.numpy()
    except Exception as e:
        print(f"Error processing {image_path}")
        print(e)
        return None


def build_dt_batch_processing(base_df, output_csv_path, batch_size=100, target_size=(224, 224)):
    
    pixel_columns = [f"pixel_{i}" for i in range(target_size[0] * target_size[1] * 3)]
    all_columns = list(base_df.columns) + pixel_columns


    # Ensure output file exists or create an empty one with headers
    if not os.path.exists(output_csv_path):
        pd.DataFrame(columns=all_columns).to_csv(output_csv_path, index=False)

    # Read existing rows from the output CSV to find processed images
    processed_images = set()
    if os.path.getsize(output_csv_path) > 0:  # Check if file is not empty
        processed_df = pd.read_csv(output_csv_path, usecols=["image"])  # Only load 'image' column
        processed_images = set(processed_df['image'].tolist())

    # Process in batches
    for i in range(0, len(base_df), batch_size):
        batch = base_df.iloc[i:i + batch_size]

        rows_to_add = []  # Store new rows to add to the CSV
        for idx, row in tqdm(batch.iterrows(), total=len(batch), desc=f"Processing batch {i // batch_size + 1}"):
            try:
                # Skip if the image is already processed
                if row['image'] in processed_images:
                    continue

                # Preprocess the image
                pixels = preprocess_image_rgn(row['image_path'], target_size=target_size)
                if pixels is None:
                    continue

                # Flatten pixels and add to row
                pixels = pixels.flatten()
                new_row = list(row) + list(pixels)
                rows_to_add.append(new_row)
            except Exception as e:
                print(f"Error processing image {row['image_path']} at index {idx}: {e}")

        # Append new rows to CSV file
        if rows_to_add:
            batch_df = pd.DataFrame(rows_to_add, columns=all_columns)
            batch_df.to_csv(output_csv_path, mode='a', header=False, index=False)
            print(f"Batch {i // batch_size + 1} saved to {output_csv_path}")

        # Update the set of processed images dynamically
        processed_images.update(batch['image'])

    print("Processing complete.")

In [ ]:
pixelated_augmented_input = os.path.join(base_project_folder, "augmented_df.csv")
augmented_df_ground_truth = pd.read_csv(augmented_df_ground_truth)
build_dt_batch_processing(augmented_df, output_csv_path=pixelated_augmented_input, batch_size=100)

augmented_df = pd.read_csv(pixelated_augmented_input)

----

In [5]:
pixelated_training_input = os.path.join(base_project_folder, "traning_df.csv")

In [ ]:
training_df = pd.read_csv(pixelated_training_input)

print(training_df.shape)
training_df.head()

In [ ]:
build_dt_batch_processing(training_ground_truth, output_csv_path=pixelated_training_input, batch_size=100)

training_df = pd.read_csv(pixelated_training_input)

print(training_df.shape)
training_df.head()

In [ ]:
chunk_size = 1000  #
for i,chunk in enumerate(pd.read_csv('./traning_df.csv', chunksize=chunk_size)):
    print(f"{i}.)")
    print(chunk.head())
    break

In [ ]:
df = pd.read_csv(pixelated_training_input)
pixel_cols = [col for col in df.columns if "pixel" in col]
other_cols = [col for col in df.columns if "pixel" not in col]

print(f"pixel col count: {len(pixel_cols)}")
print(f"other col count: {other_cols}")
df.shape

---

In [13]:
pixelated_validation_input = os.path.join(base_project_folder, "validation_df.csv")

In [ ]:
build_dt_batch_processing(validation_ground_truth, output_csv_path=pixelated_validation_input, batch_size=50)

validation_df = pd.read_csv(pixelated_validation_input)

print(validation_df.shape)
validation_df.head()

In [ ]:
pixelated_test_input = os.path.join(base_project_folder, "test_df.csv")

build_dt_batch_processing(test_ground_truth, output_csv_path=pixelated_test_input, batch_size=50)

test_df = pd.read_csv(pixelated_test_input)

print(test_df.shape)
test_df.head()

--------------

In [6]:
os.listdir("./")

['backups_models',
 'ISIC2018_Task3_Test_GroundTruth.csv',
 'ISIC2018_Task3_Test_Input',
 'ISIC2018_Task3_Training_GroundTruth.csv',
 'ISIC2018_Task3_Training_Input',
 'ISIC2018_Task3_Validation_GroundTruth.csv',
 'ISIC2018_Task3_Validation_Input',
 'main.py',
 'myenv',
 'NN_training.ipynb',
 'ordered_test_df.csv',
 'ordered_training_df.csv',
 'ordered_validation_df.csv',
 'plain_model.h5',
 'plain_model.keras',
 'plain_model_with_balancing.h5',
 'preparation.ipynb',
 'test_df.csv',
 'training_df.csv',
 'validation_df.csv']

In [56]:
# Define the function to rename the pixel columns
def rename_pixel_columns(columns):
    renamed_columns = []
    pixel_index = 0
    for col in columns:
        if col.startswith("pixel_"):
            # Determine the RGB channel (r, g, b)
            channel = ["r", "g", "b"][pixel_index % 3]
            renamed_columns.append(f"pixel_{pixel_index // 3}_{channel}")
            pixel_index += 1
        else:
            renamed_columns.append(col)
    return renamed_columns

In [15]:
# Input and output file paths
input_csv = "./training_df.csv"
output_csv = "./ordered_training_df.csv"

# Process the file to rename only the header
with open(input_csv, "r") as infile, open(output_csv, "w") as outfile:
    # Read the header (first line)
    header = infile.readline().strip().split(",")
    # Rename the columns
    new_header = rename_pixel_columns(header)
    # Write the new header to the output file
    outfile.write(",".join(new_header) + "\n")
    # Append the rest of the file line-by-line
    for line in infile:
        outfile.write(line)

In [12]:
input_csv = "./validation_df.csv"
output_csv = "./ordered_validation_df.csv"

# Process the file to rename only the header
with open(input_csv, "r") as infile, open(output_csv, "w") as outfile:
    # Read the header (first line)
    header = infile.readline().strip().split(",")
    # Rename the columns
    new_header = rename_pixel_columns(header)
    # Write the new header to the output file
    outfile.write(",".join(new_header) + "\n")
    # Append the rest of the file line-by-line
    for line in infile:
        outfile.write(line)

In [13]:
input_csv = "./test_df.csv"
output_csv = "./ordered_test_df.csv"

# Process the file to rename only the header
with open(input_csv, "r") as infile, open(output_csv, "w") as outfile:
    # Read the header (first line)
    header = infile.readline().strip().split(",")
    # Rename the columns
    new_header = rename_pixel_columns(header)
    # Write the new header to the output file
    outfile.write(",".join(new_header) + "\n")
    # Append the rest of the file line-by-line
    for line in infile:
        outfile.write(line)

----

In [4]:
header = []
with open(output_csv, "r") as infile:
    # Read the header (first line)
    header = infile.readline().strip().split(",")

In [ ]:
print(header[:15])
len(header)

------

In [1]:
import pandas as pd
from PIL import Image
from torchvision import transforms
import os
import shutil

In [6]:
base_project_folder = "./"

os.listdir(base_project_folder)

['augmented..csv',
 'augmented_df_3000_ground_truth.csv',
 'augmented_df_ground_truth.csv',
 'augmented_images',
 'augmented_images_3000',
 'augmented_new_vers',
 'backups_models',
 'ISIC2018_Task3_Test_GroundTruth.csv',
 'ISIC2018_Task3_Test_Input',
 'ISIC2018_Task3_Training_GroundTruth.csv',
 'ISIC2018_Task3_Training_Input',
 'ISIC2018_Task3_Validation_GroundTruth.csv',
 'ISIC2018_Task3_Validation_Input',
 'main.py',
 'myenv',
 'NN_training aug_also_top.ipynb',
 'NN_training.ipynb',
 'NN_training_with_rejector_mech.ipynb',
 'ordered_augmented_df.csv',
 'ordered_augmented_df_3000_unshuffeled.csv',
 'ordered_test_df.csv',
 'ordered_training_df.csv',
 'ordered_training_df_upper_limit_1500.csv',
 'ordered_training_df_upper_limit_3000.csv',
 'ordered_tranining_merged_3000.csv',
 'ordered_tranining_merged_3000.csv.zip',
 'ordered_validation_df.csv',
 'pixelated_augmented_3000.csv',
 'plain_model.h5',
 'plain_model.keras',
 'plain_model_best_perfoming.h5',
 'plain_model_with_augmentation_1000_upper_limit_1500.h5',
 'plain_model_with_augmentation_1000_upper_limit_3000.h5',
 'plain_model_with_balancing.h5',
 'plain_model_with_fin_ver.h5',
 'plain_model_with_shuffle_augmentation.h5',
 'plain_model_with_shuffle_augmentation_3000.h5',
 'preparation copy.ipynb',
 'preparation.ipynb',
 'seperation_data_by_rejection_sets_creation.ipynb',
 'test_df.csv',
 'training_df.csv',
 'training_diff_thresholds',
 'training_diff_thresholds - Copy',
 'validation_df.csv']

In [7]:
training_ground_truth = pd.read_csv(f"{base_project_folder}ISIC2018_Task3_Training_GroundTruth.csv")
training_ground_truth['image_path'] = training_ground_truth['image'].apply(lambda x: f"{base_project_folder}ISIC2018_Task3_Training_Input/{x}.jpg") 
print(training_ground_truth.head())

          image  MEL   NV  BCC  AKIEC  BKL   DF  VASC  \
0  ISIC_0024306  0.0  1.0  0.0    0.0  0.0  0.0   0.0
1  ISIC_0024307  0.0  1.0  0.0    0.0  0.0  0.0   0.0
2  ISIC_0024308  0.0  1.0  0.0    0.0  0.0  0.0   0.0
3  ISIC_0024309  0.0  1.0  0.0    0.0  0.0  0.0   0.0
4  ISIC_0024310  1.0  0.0  0.0    0.0  0.0  0.0   0.0

                                         image_path
0  ./ISIC2018_Task3_Training_Input/ISIC_0024306.jpg
1  ./ISIC2018_Task3_Training_Input/ISIC_0024307.jpg
2  ./ISIC2018_Task3_Training_Input/ISIC_0024308.jpg
3  ./ISIC2018_Task3_Training_Input/ISIC_0024309.jpg
4  ./ISIC2018_Task3_Training_Input/ISIC_0024310.jpg

In [8]:
class_distribution = training_ground_truth.drop(['image', 'image_path'], axis=1).sum(axis=0)
print(class_distribution)

MEL      1113.0
NV       6705.0
BCC       514.0
AKIEC     327.0
BKL      1099.0
DF        115.0
VASC      142.0
dtype: float64

In [9]:
training_ground_truth.head()

,image,MEL,NV,BCC,AKIEC,BKL,DF,VASC,image_path
0,ISIC_0024306,0.0,1.0,0.0,0.0,0.0,0.0,0.0,./ISIC2018_Task3_Training_Input/ISIC_0024306.jpg
1,ISIC_0024307,0.0,1.0,0.0,0.0,0.0,0.0,0.0,./ISIC2018_Task3_Training_Input/ISIC_0024307.jpg
2,ISIC_0024308,0.0,1.0,0.0,0.0,0.0,0.0,0.0,./ISIC2018_Task3_Training_Input/ISIC_0024308.jpg
3,ISIC_0024309,0.0,1.0,0.0,0.0,0.0,0.0,0.0,./ISIC2018_Task3_Training_Input/ISIC_0024309.jpg
4,ISIC_0024310,1.0,0.0,0.0,0.0,0.0,0.0,0.0,./ISIC2018_Task3_Training_Input/ISIC_0024310.jpg

In [15]:
from torchvision import transforms

def augment_image(image_path, num_augmentations=5):
    image = Image.open(image_path).convert("RGB")
    augmented_images = []
    
    for _ in range(num_augmentations):
        augmented_images.append(augmentation_transform(image))
    
    return augmented_images



augmentation_transform = transforms.Compose([
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(15),
    transforms.RandomResizedCrop(128, scale=(0.8, 1.0)),
    transforms.ColorJitter(brightness=0.3, contrast=0.3),
    transforms.RandomAffine(degrees=10, shear=5),
    transforms.GaussianBlur(kernel_size=3, sigma=(0.1, 1.0)),
    transforms.RandomErasing(p=0.2, scale=(0.02, 0.1))
])

In [11]:
minority_classes = class_distribution[class_distribution == class_distribution.min()].index.tolist()
print("Minority classes:", minority_classes)

Minority classes: ['DF']

In [12]:
augmented_images_dir = './augmented_new_vers/'
if not os.path.exists(augmented_images_dir):
    os.makedirs(augmented_images_dir)

In [13]:
augmented_images_dir

'./augmented_new_vers/'

MEL      1113.0
NV       6705.0
BCC       514.0
AKIEC     327.0
BKL      1099.0
DF        115.0
VASC      142.0

In [ ]:
augmented_data = []

minor_class = [["VASC"], ["DF"], ["BCC"], ["AKIEC"], ["BCC"]]
num_augmentations = [9, 9, 2, 3, 2]

for classes_index, minority_classes in enumerate(minor_class):
    for index, row in training_ground_truth.iterrows():
        # If the row corresponds to one of the minority classes (has a 1 in any of the minority columns)``
        if row[minority_classes].sum() > 0:
            image_path = row['image_path']
            augmented_images = augment_image(image_path, num_augmentations=num_augmentations[classes_index])
            
            # Create new rows for the augmented images with the same labels
            for i, augmented_image in enumerate(augmented_images):
                new_image_name = f"{row['image']}_aug_{i}.jpg"
                augmented_image_path = os.path.join(augmented_images_dir, new_image_name)  # Use full path
                
                # Save augmented image (optional, if you want to save it as a new file)
                augmented_image.save(augmented_image_path)
                
                # Add new row with the augmented image
                augmented_row = row.copy()
                augmented_row['image_path'] = augmented_image_path
                augmented_row['image'] = new_image_name  # Or you can keep the original name if preferred
                
                augmented_data.append(augmented_row)

AttributeError: 'Image' object has no attribute 'shape'

In [31]:
augmented_df = pd.DataFrame(augmented_data)
balanced_df = pd.concat([training_ground_truth, augmented_df], ignore_index=True)

In [32]:
balanced_df

,image,MEL,NV,BCC,AKIEC,BKL,DF,VASC,image_path
0,ISIC_0024306,0.0,1.0,0.0,0.0,0.0,0.0,0.0,./ISIC2018_Task3_Training_Input/ISIC_0024306.jpg
1,ISIC_0024307,0.0,1.0,0.0,0.0,0.0,0.0,0.0,./ISIC2018_Task3_Training_Input/ISIC_0024307.jpg
2,ISIC_0024308,0.0,1.0,0.0,0.0,0.0,0.0,0.0,./ISIC2018_Task3_Training_Input/ISIC_0024308.jpg
3,ISIC_0024309,0.0,1.0,0.0,0.0,0.0,0.0,0.0,./ISIC2018_Task3_Training_Input/ISIC_0024309.jpg
4,ISIC_0024310,1.0,0.0,0.0,0.0,0.0,0.0,0.0,./ISIC2018_Task3_Training_Input/ISIC_0024310.jpg
...,...,...,...,...,...,...,...,...,...
15360,ISIC_0034276_aug_1.jpg,0.0,0.0,1.0,0.0,0.0,0.0,0.0,./augmented_images/ISIC_0034276_aug_1.jpg
15361,ISIC_0034299_aug_0.jpg,0.0,0.0,1.0,0.0,0.0,0.0,0.0,./augmented_images/ISIC_0034299_aug_0.jpg
15362,ISIC_0034299_aug_1.jpg,0.0,0.0,1.0,0.0,0.0,0.0,0.0,./augmented_images/ISIC_0034299_aug_1.jpg
15363,ISIC_0034306_aug_0.jpg,0.0,0.0,1.0,0.0,0.0,0.0,0.0,./augmented_images/ISIC_0034306_aug_0.jpg
15364,ISIC_0034306_aug_1.jpg,0.0,0.0,1.0,0.0,0.0,0.0,0.0,./augmented_images/ISIC_0034306_aug_1.jpg

In [33]:
augmented_df[augmented_df["image"].str.contains("ISIC_0034169")]

,image,MEL,NV,BCC,AKIEC,BKL,DF,VASC,image_path
9863,ISIC_0034169_aug_0.jpg,0.0,0.0,0.0,0.0,0.0,1.0,0.0,./augmented_images/ISIC_0034169_aug_0.jpg
9863,ISIC_0034169_aug_1.jpg,0.0,0.0,0.0,0.0,0.0,1.0,0.0,./augmented_images/ISIC_0034169_aug_1.jpg
9863,ISIC_0034169_aug_2.jpg,0.0,0.0,0.0,0.0,0.0,1.0,0.0,./augmented_images/ISIC_0034169_aug_2.jpg
9863,ISIC_0034169_aug_3.jpg,0.0,0.0,0.0,0.0,0.0,1.0,0.0,./augmented_images/ISIC_0034169_aug_3.jpg
9863,ISIC_0034169_aug_4.jpg,0.0,0.0,0.0,0.0,0.0,1.0,0.0,./augmented_images/ISIC_0034169_aug_4.jpg
9863,ISIC_0034169_aug_5.jpg,0.0,0.0,0.0,0.0,0.0,1.0,0.0,./augmented_images/ISIC_0034169_aug_5.jpg
9863,ISIC_0034169_aug_6.jpg,0.0,0.0,0.0,0.0,0.0,1.0,0.0,./augmented_images/ISIC_0034169_aug_6.jpg
9863,ISIC_0034169_aug_7.jpg,0.0,0.0,0.0,0.0,0.0,1.0,0.0,./augmented_images/ISIC_0034169_aug_7.jpg
9863,ISIC_0034169_aug_8.jpg,0.0,0.0,0.0,0.0,0.0,1.0,0.0,./augmented_images/ISIC_0034169_aug_8.jpg

In [34]:
training_ground_truth[training_ground_truth["image"].str.contains("ISIC_0034169")]

,image,MEL,NV,BCC,AKIEC,BKL,DF,VASC,image_path
9863,ISIC_0034169,0.0,0.0,0.0,0.0,0.0,1.0,0.0,./ISIC2018_Task3_Training_Input/ISIC_0034169.jpg

In [35]:
augmented_df.to_csv('./augmented_df_ground_truth.csv', index=False)

In [16]:

# Convert augmented data into a new DataFrame
augmented_df = pd.DataFrame(augmented_data)

# Combine original and augmented DataFrames
balanced_df = pd.concat([training_ground_truth, augmented_df], ignore_index=True)

# Check the new class distribution
print(balanced_df.drop(['image', 'image_path'], axis=1).sum(axis=0))

# Optionally, save the new balanced DataFrame and augmented images if desired
balanced_df.to_csv('balanced_training_ground_truth.csv', index=False)

# If you want to move augmented images to a specific directory:
# Ensure the 'augmented_images' folder exists
if not os.path.exists('augmented_images'):
    os.makedirs('augmented_images')

# Optional: Save augmented images
for augmented_image in augmented_data:
    image_path = augmented_image['image_path']
    new_image_path = f"./augmented_images/{augmented_image['image']}.jpg"
    shutil.copy(image_path, new_image_path)  # Save the image to the new folder

NameError: name 'augmented_data' is not defined

In [45]:
augmented_df.to_csv('./augmented_df_ground_truth.csv', index=False)

In [ ]:
augmented_df.sum(axis=0)

In [ ]:
balanced_df.sum(axis=0)

In [ ]:

minority_classes_VASC = ["VASC"]
for index, row in training_ground_truth.iterrows():
    # If the row corresponds to one of the minority classes (has a 1 in any of the minority columns)
    if row[minority_classes].sum() > 0:
        image_path = row['image_path']
        augmented_images = augment_image(image_path, num_augmentations=5)
        
        # Create new rows for the augmented images with the same labels
        for i, augmented_image in enumerate(augmented_images):
            new_image_name = f"{row['image']}_aug_{i}.jpg"
            augmented_image_path = os.path.join(augmented_images_dir, new_image_name)  # Use full path
            
            # Save augmented image (optional, if you want to save it as a new file)
            augmented_image.save(augmented_image_path)
            
            # Add new row with the augmented image
            augmented_row = row.copy()
            augmented_row['image_path'] = augmented_image_path
            augmented_row['image'] = new_image_name  # Or you can keep the original name if preferred
            
            augmented_data.append(augmented_row)

----

In [ ]:
class_distribution = training_ground_truth.drop(['image', 'image_path'], axis=1).sum(axis=0)
majority_class_size = class_distribution.max()
print(f'Majority class size: {majority_class_size}')

# List the classes
classes = class_distribution.index.tolist()

augmented_data = []

# Augment images for the minority classes to balance dataset
for class_label in classes:
    # Get the rows corresponding to the current class
    class_df = training_ground_truth[training_ground_truth[class_label] == 1]

    # Calculate how many samples we need to generate for this class
    num_augmentations_needed = majority_class_size - len(class_df)
    
    # If this class is underrepresented, apply augmentation
    if num_augmentations_needed > 0:
        print(f"Augmenting class {class_label} with {num_augmentations_needed} new samples.")
        
        for index, row in class_df.iterrows():
            image_path = row['image_path']
            augmented_images = augment_image(image_path, num_augmentations=int(num_augmentations_needed))
            
            # Create new rows for the augmented images with the same labels
            for i, augmented_image in enumerate(augmented_images):
                new_image_name = f"{row['image']}_aug_{i}.jpg"
                augmented_image_path = os.path.join('./augmented_images', new_image_name)  # Ensure dir exists
                
                # Save augmented image (optional, if you want to save it as a new file)
                augmented_image.save(augmented_image_path)
                
                # Add new row with the augmented image
                augmented_row = row.copy()
                augmented_row['image_path'] = augmented_image_path
                augmented_row['image'] = new_image_name  # Or keep the original name if preferred
                
                augmented_data.append(augmented_row)

# Convert augmented data into a new DataFrame
augmented_df = pd.DataFrame(augmented_data)

In [ ]:
# Combine original and augmented DataFrames
balanced_df = pd.concat([training_ground_truth, augmented_df], ignore_index=True)

# Check the new class distribution
balanced_class_distribution = balanced_df.drop(['image', 'image_path'], axis=1).sum(axis=0)
print("Balanced class distribution:", balanced_class_distribution)

# Save the balanced DataFrame
balanced_df.to_csv('balanced_training_ground_truth.csv', index=False)

-----

In [45]:
augmented_df.head()

,image,MEL,NV,BCC,AKIEC,BKL,DF,VASC,image_path
64,ISIC_0024370_aug_0.jpg,0.0,0.0,0.0,0.0,0.0,0.0,1.0,./augmented_images/ISIC_0024370_aug_0.jpg
64,ISIC_0024370_aug_1.jpg,0.0,0.0,0.0,0.0,0.0,0.0,1.0,./augmented_images/ISIC_0024370_aug_1.jpg
64,ISIC_0024370_aug_2.jpg,0.0,0.0,0.0,0.0,0.0,0.0,1.0,./augmented_images/ISIC_0024370_aug_2.jpg
64,ISIC_0024370_aug_3.jpg,0.0,0.0,0.0,0.0,0.0,0.0,1.0,./augmented_images/ISIC_0024370_aug_3.jpg
64,ISIC_0024370_aug_4.jpg,0.0,0.0,0.0,0.0,0.0,0.0,1.0,./augmented_images/ISIC_0024370_aug_4.jpg

In [ ]:
# pixelated_augmented_input = os.path.join(base_project_folder, "/augmented_df.csv")
# pixelated_augmented_df_input = "./augmented.csv"
pixelated_augmented_df_input =  "./augmented_new_vers.csv"
pixelated_augmented_input

'/augmented_df.csv'

In [53]:
def build_dt_batch_processing_a(base_df, output_csv_path, batch_size=100, target_size=(224, 224)):
    
    pixel_columns = [f"pixel_{i}" for i in range(target_size[0] * target_size[1] * 3)]
    all_columns = list(base_df.columns) + pixel_columns


    # Ensure output file exists or create an empty one with headers
    if not os.path.exists(output_csv_path):
        pd.DataFrame(columns=all_columns).to_csv(output_csv_path, index=False)

    # Read existing rows from the output CSV to find processed images
    processed_images = set()
    if os.path.getsize(output_csv_path) > 0:  # Check if file is not empty
        processed_df = pd.read_csv(output_csv_path, usecols=["image"])  # Only load 'image' column
        processed_images = set(processed_df['image'].tolist())

    # Process in batches
    for i in range(0, len(base_df), batch_size):
        batch = base_df.iloc[i:i + batch_size]

        rows_to_add = []  # Store new rows to add to the CSV
        for idx, row in tqdm(batch.iterrows(), total=len(batch), desc=f"Processing batch {i // batch_size + 1}"):
            try:
                # Skip if the image is already processed
                if row['image'] in processed_images:
                    continue

                # Preprocess the image
                pixels = preprocess_image_rgn(row['image_path'], target_size=target_size)
                if pixels is None:
                    continue

                # Flatten pixels and add to row
                pixels = pixels.flatten()
                new_row = list(row) + list(pixels)
                rows_to_add.append(new_row)
            except Exception as e:
                print(f"Error processing image {row['image_path']} at index {idx}: {e}")

        # Append new rows to CSV file
        if rows_to_add:
            batch_df = pd.DataFrame(rows_to_add, columns=all_columns)
            batch_df.to_csv(output_csv_path, mode='a', header=False, index=False)
            print(f"Batch {i // batch_size + 1} saved to {output_csv_path}")

        # Update the set of processed images dynamically
        processed_images.update(batch['image'])

    print("Processing complete.")

In [54]:

build_dt_batch_processing_a(augmented_df, output_csv_path=pixelated_augmented_df_input, batch_size=100)

augmented_df = pd.read_csv(pixelated_augmented_input)

Processing batch 1: 100%|██████████| 100/100 [00:00<00:00, 101.52it/s]

Batch 1 saved to ./augmented..csv

Processing batch 2: 100%|██████████| 100/100 [00:00<00:00, 106.61it/s]

Batch 2 saved to ./augmented..csv

Processing batch 3: 100%|██████████| 100/100 [00:00<00:00, 105.71it/s]

Batch 3 saved to ./augmented..csv

Processing batch 4: 100%|██████████| 100/100 [00:00<00:00, 104.82it/s]

Batch 4 saved to ./augmented..csv

Processing batch 5: 100%|██████████| 100/100 [00:00<00:00, 108.05it/s]

Batch 5 saved to ./augmented..csv

Processing batch 6: 100%|██████████| 100/100 [00:00<00:00, 108.20it/s]

Batch 6 saved to ./augmented..csv

Processing batch 7: 100%|██████████| 100/100 [00:00<00:00, 109.17it/s]

Batch 7 saved to ./augmented..csv

Processing batch 8: 100%|██████████| 100/100 [00:00<00:00, 103.63it/s]

Batch 8 saved to ./augmented..csv

Processing batch 9: 100%|██████████| 100/100 [00:01<00:00, 99.66it/s]

Batch 9 saved to ./augmented..csv

Processing batch 10: 100%|██████████| 100/100 [00:01<00:00, 99.70it/s]

Batch 10 saved to ./augmented..csv

Processing batch 11: 100%|██████████| 100/100 [00:01<00:00, 97.56it/s]

Batch 11 saved to ./augmented..csv

Processing batch 12: 100%|██████████| 100/100 [00:01<00:00, 97.18it/s]

Batch 12 saved to ./augmented..csv

Processing batch 13: 100%|██████████| 100/100 [00:00<00:00, 104.49it/s]

Batch 13 saved to ./augmented..csv

Processing batch 14: 100%|██████████| 100/100 [00:00<00:00, 101.42it/s]

Batch 14 saved to ./augmented..csv

Processing batch 15: 100%|██████████| 100/100 [00:00<00:00, 104.71it/s]

Batch 15 saved to ./augmented..csv

Processing batch 16: 100%|██████████| 100/100 [00:00<00:00, 108.46it/s]

Batch 16 saved to ./augmented..csv

Processing batch 17: 100%|██████████| 100/100 [00:00<00:00, 107.18it/s]

Batch 17 saved to ./augmented..csv

Processing batch 18: 100%|██████████| 100/100 [00:00<00:00, 105.15it/s]

Batch 18 saved to ./augmented..csv

Processing batch 19: 100%|██████████| 100/100 [00:00<00:00, 102.35it/s]

Batch 19 saved to ./augmented..csv

Processing batch 20: 100%|██████████| 100/100 [00:00<00:00, 105.93it/s]

Batch 20 saved to ./augmented..csv

Processing batch 21: 100%|██████████| 100/100 [00:00<00:00, 108.34it/s]

Batch 21 saved to ./augmented..csv

Processing batch 22: 100%|██████████| 100/100 [00:00<00:00, 108.70it/s]

Batch 22 saved to ./augmented..csv

Processing batch 23: 100%|██████████| 100/100 [00:00<00:00, 108.37it/s]

Batch 23 saved to ./augmented..csv

Processing batch 24: 100%|██████████| 100/100 [00:00<00:00, 105.82it/s]

Batch 24 saved to ./augmented..csv

Processing batch 25: 100%|██████████| 100/100 [00:00<00:00, 108.81it/s]

Batch 25 saved to ./augmented..csv

Processing batch 26: 100%|██████████| 100/100 [00:00<00:00, 108.44it/s]

Batch 26 saved to ./augmented..csv

Processing batch 27: 100%|██████████| 100/100 [00:00<00:00, 102.25it/s]

Batch 27 saved to ./augmented..csv

Processing batch 28: 100%|██████████| 100/100 [00:00<00:00, 108.86it/s]

Batch 28 saved to ./augmented..csv

Processing batch 29: 100%|██████████| 100/100 [00:00<00:00, 108.58it/s]

Batch 29 saved to ./augmented..csv

Processing batch 30: 100%|██████████| 100/100 [00:00<00:00, 103.95it/s]

Batch 30 saved to ./augmented..csv

Processing batch 31: 100%|██████████| 100/100 [00:00<00:00, 103.52it/s]

Batch 31 saved to ./augmented..csv

Processing batch 32: 100%|██████████| 100/100 [00:00<00:00, 107.99it/s]

Batch 32 saved to ./augmented..csv

Processing batch 33: 100%|██████████| 100/100 [00:00<00:00, 108.23it/s]

Batch 33 saved to ./augmented..csv

Processing batch 34: 100%|██████████| 100/100 [00:00<00:00, 106.45it/s]

Batch 34 saved to ./augmented..csv

Processing batch 35: 100%|██████████| 100/100 [00:00<00:00, 107.93it/s]

Batch 35 saved to ./augmented..csv

Processing batch 36: 100%|██████████| 100/100 [00:00<00:00, 105.26it/s]

Batch 36 saved to ./augmented..csv

Processing batch 37: 100%|██████████| 100/100 [00:00<00:00, 103.41it/s]

Batch 37 saved to ./augmented..csv

Processing batch 38: 100%|██████████| 100/100 [00:00<00:00, 108.13it/s]

Batch 38 saved to ./augmented..csv

Processing batch 39: 100%|██████████| 100/100 [00:00<00:00, 106.84it/s]

Batch 39 saved to ./augmented..csv

Processing batch 40: 100%|██████████| 100/100 [00:00<00:00, 108.34it/s]

Batch 40 saved to ./augmented..csv

Processing batch 41: 100%|██████████| 100/100 [00:00<00:00, 108.87it/s]

Batch 41 saved to ./augmented..csv

Processing batch 42: 100%|██████████| 100/100 [00:00<00:00, 107.64it/s]

Batch 42 saved to ./augmented..csv

Processing batch 43: 100%|██████████| 100/100 [00:00<00:00, 105.95it/s]

Batch 43 saved to ./augmented..csv

Processing batch 44: 100%|██████████| 100/100 [00:00<00:00, 487.81it/s]

Batch 44 saved to ./augmented..csv

Processing batch 45: 100%|██████████| 100/100 [00:00<00:00, 16660.59it/s]
Processing batch 46: 100%|██████████| 100/100 [00:00<00:00, 16673.84it/s]
Processing batch 47: 100%|██████████| 100/100 [00:00<00:00, 20013.86it/s]
Processing batch 48: 100%|██████████| 100/100 [00:00<00:00, 16665.89it/s]
Processing batch 49: 100%|██████████| 100/100 [00:00<00:00, 20001.45it/s]
Processing batch 50: 100%|██████████| 100/100 [00:00<00:00, 20000.50it/s]
Processing batch 51: 100%|██████████| 100/100 [00:00<00:00, 20024.37it/s]
Processing batch 52: 100%|██████████| 100/100 [00:00<00:00, 20013.86it/s]
Processing batch 53: 100%|██████████| 100/100 [00:00<00:00, 20001.45it/s]
Processing batch 54: 100%|██████████| 50/50 [00:00<00:00, 12494.20it/s]

Processing complete.

----

In [57]:
# Input and output file paths
input_csv = "./augmented..csv"
output_csv = "./ordered_augmented._df.csv"

# Process the file to rename only the header
with open(input_csv, "r") as infile, open(output_csv, "w") as outfile:
    # Read the header (first line)
    header = infile.readline().strip().split(",")
    # Rename the columns
    new_header = rename_pixel_columns(header)
    # Write the new header to the output file
    outfile.write(",".join(new_header) + "\n")
    # Append the rest of the file line-by-line
    for line in infile:
        outfile.write(line)

In [60]:
header = []
first_row = []
with open(output_csv, "r") as infile:
    # Read the header (first line)
    header = infile.readline().strip().split(",")
    first_row = infile.readline().strip().split(",")

In [61]:
header

['image',
 'MEL',
 'NV',
 'BCC',
 'AKIEC',
 'BKL',
 'DF',
 'VASC',
 'image_path',
 'pixel_0_r',
 'pixel_0_g',
 'pixel_0_b',
 'pixel_1_r',
 'pixel_1_g',
 'pixel_1_b',
 'pixel_2_r',
 'pixel_2_g',
 'pixel_2_b',
 'pixel_3_r',
 'pixel_3_g',
 'pixel_3_b',
 'pixel_4_r',
 'pixel_4_g',
 'pixel_4_b',
 'pixel_5_r',
 'pixel_5_g',
 'pixel_5_b',
 'pixel_6_r',
 'pixel_6_g',
 'pixel_6_b',
 'pixel_7_r',
 'pixel_7_g',
 'pixel_7_b',
 'pixel_8_r',
 'pixel_8_g',
 'pixel_8_b',
 'pixel_9_r',
 'pixel_9_g',
 'pixel_9_b',
 'pixel_10_r',
 'pixel_10_g',
 'pixel_10_b',
 'pixel_11_r',
 'pixel_11_g',
 'pixel_11_b',
 'pixel_12_r',
 'pixel_12_g',
 'pixel_12_b',
 'pixel_13_r',
 'pixel_13_g',
 'pixel_13_b',
 'pixel_14_r',
 'pixel_14_g',
 'pixel_14_b',
 'pixel_15_r',
 'pixel_15_g',
 'pixel_15_b',
 'pixel_16_r',
 'pixel_16_g',
 'pixel_16_b',
 'pixel_17_r',
 'pixel_17_g',
 'pixel_17_b',
 'pixel_18_r',
 'pixel_18_g',
 'pixel_18_b',
 'pixel_19_r',
 'pixel_19_g',
 'pixel_19_b',
 'pixel_20_r',
 'pixel_20_g',
 'pixel_20_b',
 'pixel_21_r',
 'pixel_21_g',
 'pixel_21_b',
 'pixel_22_r',
 'pixel_22_g',
 'pixel_22_b',
 'pixel_23_r',
 'pixel_23_g',
 'pixel_23_b',
 'pixel_24_r',
 'pixel_24_g',
 'pixel_24_b',
 'pixel_25_r',
 'pixel_25_g',
 'pixel_25_b',
 'pixel_26_r',
 'pixel_26_g',
 'pixel_26_b',
 'pixel_27_r',
 'pixel_27_g',
 'pixel_27_b',
 'pixel_28_r',
 'pixel_28_g',
 'pixel_28_b',
 'pixel_29_r',
 'pixel_29_g',
 'pixel_29_b',
 'pixel_30_r',
 'pixel_30_g',
 'pixel_30_b',
 'pixel_31_r',
 'pixel_31_g',
 'pixel_31_b',
 'pixel_32_r',
 'pixel_32_g',
 'pixel_32_b',
 'pixel_33_r',
 'pixel_33_g',
 'pixel_33_b',
 'pixel_34_r',
 'pixel_34_g',
 'pixel_34_b',
 'pixel_35_r',
 'pixel_35_g',
 'pixel_35_b',
 'pixel_36_r',
 'pixel_36_g',
 'pixel_36_b',
 'pixel_37_r',
 'pixel_37_g',
 'pixel_37_b',
 'pixel_38_r',
 'pixel_38_g',
 'pixel_38_b',
 'pixel_39_r',
 'pixel_39_g',
 'pixel_39_b',
 'pixel_40_r',
 'pixel_40_g',
 'pixel_40_b',
 'pixel_41_r',
 'pixel_41_g',
 'pixel_41_b',
 'pixel_42_r',
 'pixel_42_g',
 'pixel_42_b',
 'pixel_43_r',
 'pixel_43_g',
 'pixel_43_b',
 'pixel_44_r',
 'pixel_44_g',
 'pixel_44_b',
 'pixel_45_r',
 'pixel_45_g',
 'pixel_45_b',
 'pixel_46_r',
 'pixel_46_g',
 'pixel_46_b',
 'pixel_47_r',
 'pixel_47_g',
 'pixel_47_b',
 'pixel_48_r',
 'pixel_48_g',
 'pixel_48_b',
 'pixel_49_r',
 'pixel_49_g',
 'pixel_49_b',
 'pixel_50_r',
 'pixel_50_g',
 'pixel_50_b',
 'pixel_51_r',
 'pixel_51_g',
 'pixel_51_b',
 'pixel_52_r',
 'pixel_52_g',
 'pixel_52_b',
 'pixel_53_r',
 'pixel_53_g',
 'pixel_53_b',
 'pixel_54_r',
 'pixel_54_g',
 'pixel_54_b',
 'pixel_55_r',
 'pixel_55_g',
 'pixel_55_b',
 'pixel_56_r',
 'pixel_56_g',
 'pixel_56_b',
 'pixel_57_r',
 'pixel_57_g',
 'pixel_57_b',
 'pixel_58_r',
 'pixel_58_g',
 'pixel_58_b',
 'pixel_59_r',
 'pixel_59_g',
 'pixel_59_b',
 'pixel_60_r',
 'pixel_60_g',
 'pixel_60_b',
 'pixel_61_r',
 'pixel_61_g',
 'pixel_61_b',
 'pixel_62_r',
 'pixel_62_g',
 'pixel_62_b',
 'pixel_63_r',
 'pixel_63_g',
 'pixel_63_b',
 'pixel_64_r',
 'pixel_64_g',
 'pixel_64_b',
 'pixel_65_r',
 'pixel_65_g',
 'pixel_65_b',
 'pixel_66_r',
 'pixel_66_g',
 'pixel_66_b',
 'pixel_67_r',
 'pixel_67_g',
 'pixel_67_b',
 'pixel_68_r',
 'pixel_68_g',
 'pixel_68_b',
 'pixel_69_r',
 'pixel_69_g',
 'pixel_69_b',
 'pixel_70_r',
 'pixel_70_g',
 'pixel_70_b',
 'pixel_71_r',
 'pixel_71_g',
 'pixel_71_b',
 'pixel_72_r',
 'pixel_72_g',
 'pixel_72_b',
 'pixel_73_r',
 'pixel_73_g',
 'pixel_73_b',
 'pixel_74_r',
 'pixel_74_g',
 'pixel_74_b',
 'pixel_75_r',
 'pixel_75_g',
 'pixel_75_b',
 'pixel_76_r',
 'pixel_76_g',
 'pixel_76_b',
 'pixel_77_r',
 'pixel_77_g',
 'pixel_77_b',
 'pixel_78_r',
 'pixel_78_g',
 'pixel_78_b',
 'pixel_79_r',
 'pixel_79_g',
 'pixel_79_b',
 'pixel_80_r',
 'pixel_80_g',
 'pixel_80_b',
 'pixel_81_r',
 'pixel_81_g',
 'pixel_81_b',
 'pixel_82_r',
 'pixel_82_g',
 'pixel_82_b',
 'pixel_83_r',
 'pixel_83_g',
 'pixel_83_b',
 'pixel_84_r',
 'pixel_84_g',
 'pixel_84_b',
 'pixel_85_r',
 'pixel_85_g',
 'pixel_85_b',
 'pixel_86_r',
 'pixel_86_g',
 'pixel_86_b',
 'pixel_87_r',
 'pixel_87_g',
 'pixel_87_b',
 'pixel_88_r',
 'pixel_88_g',
 'pixel_88_b',
 'pixel_89_r',
 'pixel_89_g',
 'pixel_89_b',
 'pixel_90_r',
 'pixel_90_g',
 'pixel_90_b',
 'pixel_91_r',
 'pixel_91_g',
 'pixel_91_b',
 'pixel_92_r',
 'pixel_92_g',
 'pixel_92_b',
 'pixel_93_r',
 'pixel_93_g',
 'pixel_93_b',
 'pixel_94_r',
 'pixel_94_g',
 'pixel_94_b',
 'pixel_95_r',
 'pixel_95_g',
 'pixel_95_b',
 'pixel_96_r',
 'pixel_96_g',
 'pixel_96_b',
 'pixel_97_r',
 'pixel_97_g',
 'pixel_97_b',
 'pixel_98_r',
 'pixel_98_g',
 'pixel_98_b',
 'pixel_99_r',
 'pixel_99_g',
 'pixel_99_b',
 'pixel_100_r',
 'pixel_100_g',
 'pixel_100_b',
 'pixel_101_r',
 'pixel_101_g',
 'pixel_101_b',
 'pixel_102_r',
 'pixel_102_g',
 'pixel_102_b',
 'pixel_103_r',
 'pixel_103_g',
 'pixel_103_b',
 'pixel_104_r',
 'pixel_104_g',
 'pixel_104_b',
 'pixel_105_r',
 'pixel_105_g',
 'pixel_105_b',
 'pixel_106_r',
 'pixel_106_g',
 'pixel_106_b',
 'pixel_107_r',
 'pixel_107_g',
 'pixel_107_b',
 'pixel_108_r',
 'pixel_108_g',
 'pixel_108_b',
 'pixel_109_r',
 'pixel_109_g',
 'pixel_109_b',
 'pixel_110_r',
 'pixel_110_g',
 'pixel_110_b',
 'pixel_111_r',
 'pixel_111_g',
 'pixel_111_b',
 'pixel_112_r',
 'pixel_112_g',
 'pixel_112_b',
 'pixel_113_r',
 'pixel_113_g',
 'pixel_113_b',
 'pixel_114_r',
 'pixel_114_g',
 'pixel_114_b',
 'pixel_115_r',
 'pixel_115_g',
 'pixel_115_b',
 'pixel_116_r',
 'pixel_116_g',
 'pixel_116_b',
 'pixel_117_r',
 'pixel_117_g',
 'pixel_117_b',
 'pixel_118_r',
 'pixel_118_g',
 'pixel_118_b',
 'pixel_119_r',
 'pixel_119_g',
 'pixel_119_b',
 'pixel_120_r',
 'pixel_120_g',
 'pixel_120_b',
 'pixel_121_r',
 'pixel_121_g',
 'pixel_121_b',
 'pixel_122_r',
 'pixel_122_g',
 'pixel_122_b',
 'pixel_123_r',
 'pixel_123_g',
 'pixel_123_b',
 'pixel_124_r',
 'pixel_124_g',
 'pixel_124_b',
 'pixel_125_r',
 'pixel_125_g',
 'pixel_125_b',
 'pixel_126_r',
 'pixel_126_g',
 'pixel_126_b',
 'pixel_127_r',
 'pixel_127_g',
 'pixel_127_b',
 'pixel_128_r',
 'pixel_128_g',
 'pixel_128_b',
 'pixel_129_r',
 'pixel_129_g',
 'pixel_129_b',
 'pixel_130_r',
 'pixel_130_g',
 'pixel_130_b',
 'pixel_131_r',
 'pixel_131_g',
 'pixel_131_b',
 'pixel_132_r',
 'pixel_132_g',
 'pixel_132_b',
 'pixel_133_r',
 'pixel_133_g',
 'pixel_133_b',
 'pixel_134_r',
 'pixel_134_g',
 'pixel_134_b',
 'pixel_135_r',
 'pixel_135_g',
 'pixel_135_b',
 'pixel_136_r',
 'pixel_136_g',
 'pixel_136_b',
 'pixel_137_r',
 'pixel_137_g',
 'pixel_137_b',
 'pixel_138_r',
 'pixel_138_g',
 'pixel_138_b',
 'pixel_139_r',
 'pixel_139_g',
 'pixel_139_b',
 'pixel_140_r',
 'pixel_140_g',
 'pixel_140_b',
 'pixel_141_r',
 'pixel_141_g',
 'pixel_141_b',
 'pixel_142_r',
 'pixel_142_g',
 'pixel_142_b',
 'pixel_143_r',
 'pixel_143_g',
 'pixel_143_b',
 'pixel_144_r',
 'pixel_144_g',
 'pixel_144_b',
 'pixel_145_r',
 'pixel_145_g',
 'pixel_145_b',
 'pixel_146_r',
 'pixel_146_g',
 'pixel_146_b',
 'pixel_147_r',
 'pixel_147_g',
 'pixel_147_b',
 'pixel_148_r',
 'pixel_148_g',
 'pixel_148_b',
 'pixel_149_r',
 'pixel_149_g',
 'pixel_149_b',
 'pixel_150_r',
 'pixel_150_g',
 'pixel_150_b',
 'pixel_151_r',
 'pixel_151_g',
 'pixel_151_b',
 'pixel_152_r',
 'pixel_152_g',
 'pixel_152_b',
 'pixel_153_r',
 'pixel_153_g',
 'pixel_153_b',
 'pixel_154_r',
 'pixel_154_g',
 'pixel_154_b',
 'pixel_155_r',
 'pixel_155_g',
 'pixel_155_b',
 'pixel_156_r',
 'pixel_156_g',
 'pixel_156_b',
 'pixel_157_r',
 'pixel_157_g',
 'pixel_157_b',
 'pixel_158_r',
 'pixel_158_g',
 'pixel_158_b',
 'pixel_159_r',
 'pixel_159_g',
 'pixel_159_b',
 'pixel_160_r',
 'pixel_160_g',
 'pixel_160_b',
 'pixel_161_r',
 'pixel_161_g',
 'pixel_161_b',
 'pixel_162_r',
 'pixel_162_g',
 'pixel_162_b',
 'pixel_163_r',
 'pixel_163_g',
 'pixel_163_b',
 'pixel_164_r',
 'pixel_164_g',
 'pixel_164_b',
 'pixel_165_r',
 'pixel_165_g',
 'pixel_165_b',
 'pixel_166_r',
 'pixel_166_g',
 'pixel_166_b',
 'pixel_167_r',
 'pixel_167_g',
 'pixel_167_b',
 'pixel_168_r',
 'pixel_168_g',
 'pixel_168_b',
 'pixel_169_r',
 'pixel_169_g',
 'pixel_169_b',
 'pixel_170_r',
 'pixel_170_g',
 'pixel_170_b',
 'pixel_171_r',
 'pixel_171_g',
 'pixel_171_b',
 'pixel_172_r',
 'pixel_172_g',
 'pixel_172_b',
 'pixel_173_r',
 'pixel_173_g',
 'pixel_173_b',
 'pixel_174_r',
 'pixel_174_g',
 'pixel_174_b',
 'pixel_175_r',
 'pixel_175_g',
 'pixel_175_b',
 'pixel_176_r',
 'pixel_176_g',
 'pixel_176_b',
 'pixel_177_r',
 'pixel_177_g',
 'pixel_177_b',
 'pixel_178_r',
 'pixel_178_g',
 'pixel_178_b',
 'pixel_179_r',
 'pixel_179_g',
 'pixel_179_b',
 'pixel_180_r',
 'pixel_180_g',
 'pixel_180_b',
 'pixel_181_r',
 'pixel_181_g',
 'pixel_181_b',
 'pixel_182_r',
 'pixel_182_g',
 'pixel_182_b',
 'pixel_183_r',
 'pixel_183_g',
 'pixel_183_b',
 'pixel_184_r',
 'pixel_184_g',
 'pixel_184_b',
 'pixel_185_r',
 'pixel_185_g',
 'pixel_185_b',
 'pixel_186_r',
 'pixel_186_g',
 'pixel_186_b',
 'pixel_187_r',
 'pixel_187_g',
 'pixel_187_b',
 'pixel_188_r',
 'pixel_188_g',
 'pixel_188_b',
 'pixel_189_r',
 'pixel_189_g',
 'pixel_189_b',
 'pixel_190_r',
 'pixel_190_g',
 'pixel_190_b',
 'pixel_191_r',
 'pixel_191_g',
 'pixel_191_b',
 'pixel_192_r',
 'pixel_192_g',
 'pixel_192_b',
 'pixel_193_r',
 'pixel_193_g',
 'pixel_193_b',
 'pixel_194_r',
 'pixel_194_g',
 'pixel_194_b',
 'pixel_195_r',
 'pixel_195_g',
 'pixel_195_b',
 'pixel_196_r',
 'pixel_196_g',
 'pixel_196_b',
 'pixel_197_r',
 'pixel_197_g',
 'pixel_197_b',
 'pixel_198_r',
 'pixel_198_g',
 'pixel_198_b',
 'pixel_199_r',
 'pixel_199_g',
 'pixel_199_b',
 'pixel_200_r',
 'pixel_200_g',
 'pixel_200_b',
 'pixel_201_r',
 'pixel_201_g',
 'pixel_201_b',
 'pixel_202_r',
 'pixel_202_g',
 'pixel_202_b',
 'pixel_203_r',
 'pixel_203_g',
 'pixel_203_b',
 'pixel_204_r',
 'pixel_204_g',
 'pixel_204_b',
 'pixel_205_r',
 'pixel_205_g',
 'pixel_205_b',
 'pixel_206_r',
 'pixel_206_g',
 'pixel_206_b',
 'pixel_207_r',
 'pixel_207_g',
 'pixel_207_b',
 'pixel_208_r',
 'pixel_208_g',
 'pixel_208_b',
 'pixel_209_r',
 'pixel_209_g',
 'pixel_209_b',
 'pixel_210_r',
 'pixel_210_g',
 'pixel_210_b',
 'pixel_211_r',
 'pixel_211_g',
 'pixel_211_b',
 'pixel_212_r',
 'pixel_212_g',
 'pixel_212_b',
 'pixel_213_r',
 'pixel_213_g',
 'pixel_213_b',
 'pixel_214_r',
 'pixel_214_g',
 'pixel_214_b',
 'pixel_215_r',
 'pixel_215_g',
 'pixel_215_b',
 'pixel_216_r',
 'pixel_216_g',
 'pixel_216_b',
 'pixel_217_r',
 'pixel_217_g',
 'pixel_217_b',
 'pixel_218_r',
 'pixel_218_g',
 'pixel_218_b',
 'pixel_219_r',
 'pixel_219_g',
 'pixel_219_b',
 'pixel_220_r',
 'pixel_220_g',
 'pixel_220_b',
 'pixel_221_r',
 'pixel_221_g',
 'pixel_221_b',
 'pixel_222_r',
 'pixel_222_g',
 'pixel_222_b',
 'pixel_223_r',
 'pixel_223_g',
 'pixel_223_b',
 'pixel_224_r',
 'pixel_224_g',
 'pixel_224_b',
 'pixel_225_r',
 'pixel_225_g',
 'pixel_225_b',
 'pixel_226_r',
 'pixel_226_g',
 'pixel_226_b',
 'pixel_227_r',
 'pixel_227_g',
 'pixel_227_b',
 'pixel_228_r',
 'pixel_228_g',
 'pixel_228_b',
 'pixel_229_r',
 'pixel_229_g',
 'pixel_229_b',
 'pixel_230_r',
 'pixel_230_g',
 'pixel_230_b',
 'pixel_231_r',
 'pixel_231_g',
 'pixel_231_b',
 'pixel_232_r',
 'pixel_232_g',
 'pixel_232_b',
 'pixel_233_r',
 'pixel_233_g',
 'pixel_233_b',
 'pixel_234_r',
 'pixel_234_g',
 'pixel_234_b',
 'pixel_235_r',
 'pixel_235_g',
 'pixel_235_b',
 'pixel_236_r',
 'pixel_236_g',
 'pixel_236_b',
 'pixel_237_r',
 'pixel_237_g',
 'pixel_237_b',
 'pixel_238_r',
 'pixel_238_g',
 'pixel_238_b',
 'pixel_239_r',
 'pixel_239_g',
 'pixel_239_b',
 'pixel_240_r',
 'pixel_240_g',
 'pixel_240_b',
 'pixel_241_r',
 'pixel_241_g',
 'pixel_241_b',
 'pixel_242_r',
 'pixel_242_g',
 'pixel_242_b',
 'pixel_243_r',
 'pixel_243_g',
 'pixel_243_b',
 'pixel_244_r',
 'pixel_244_g',
 'pixel_244_b',
 'pixel_245_r',
 'pixel_245_g',
 'pixel_245_b',
 'pixel_246_r',
 'pixel_246_g',
 'pixel_246_b',
 'pixel_247_r',
 'pixel_247_g',
 'pixel_247_b',
 'pixel_248_r',
 'pixel_248_g',
 'pixel_248_b',
 'pixel_249_r',
 'pixel_249_g',
 'pixel_249_b',
 'pixel_250_r',
 'pixel_250_g',
 'pixel_250_b',
 'pixel_251_r',
 'pixel_251_g',
 'pixel_251_b',
 'pixel_252_r',
 'pixel_252_g',
 'pixel_252_b',
 'pixel_253_r',
 'pixel_253_g',
 'pixel_253_b',
 'pixel_254_r',
 'pixel_254_g',
 'pixel_254_b',
 'pixel_255_r',
 'pixel_255_g',
 'pixel_255_b',
 'pixel_256_r',
 'pixel_256_g',
 'pixel_256_b',
 'pixel_257_r',
 'pixel_257_g',
 'pixel_257_b',
 'pixel_258_r',
 'pixel_258_g',
 'pixel_258_b',
 'pixel_259_r',
 'pixel_259_g',
 'pixel_259_b',
 'pixel_260_r',
 'pixel_260_g',
 'pixel_260_b',
 'pixel_261_r',
 'pixel_261_g',
 'pixel_261_b',
 'pixel_262_r',
 'pixel_262_g',
 'pixel_262_b',
 'pixel_263_r',
 'pixel_263_g',
 'pixel_263_b',
 'pixel_264_r',
 'pixel_264_g',
 'pixel_264_b',
 'pixel_265_r',
 'pixel_265_g',
 'pixel_265_b',
 'pixel_266_r',
 'pixel_266_g',
 'pixel_266_b',
 'pixel_267_r',
 'pixel_267_g',
 'pixel_267_b',
 'pixel_268_r',
 'pixel_268_g',
 'pixel_268_b',
 'pixel_269_r',
 'pixel_269_g',
 'pixel_269_b',
 'pixel_270_r',
 'pixel_270_g',
 'pixel_270_b',
 'pixel_271_r',
 'pixel_271_g',
 'pixel_271_b',
 'pixel_272_r',
 'pixel_272_g',
 'pixel_272_b',
 'pixel_273_r',
 'pixel_273_g',
 'pixel_273_b',
 'pixel_274_r',
 'pixel_274_g',
 'pixel_274_b',
 'pixel_275_r',
 'pixel_275_g',
 'pixel_275_b',
 'pixel_276_r',
 'pixel_276_g',
 'pixel_276_b',
 'pixel_277_r',
 'pixel_277_g',
 'pixel_277_b',
 'pixel_278_r',
 'pixel_278_g',
 'pixel_278_b',
 'pixel_279_r',
 'pixel_279_g',
 'pixel_279_b',
 'pixel_280_r',
 'pixel_280_g',
 'pixel_280_b',
 'pixel_281_r',
 'pixel_281_g',
 'pixel_281_b',
 'pixel_282_r',
 'pixel_282_g',
 'pixel_282_b',
 'pixel_283_r',
 'pixel_283_g',
 'pixel_283_b',
 'pixel_284_r',
 'pixel_284_g',
 'pixel_284_b',
 'pixel_285_r',
 'pixel_285_g',
 'pixel_285_b',
 'pixel_286_r',
 'pixel_286_g',
 'pixel_286_b',
 'pixel_287_r',
 'pixel_287_g',
 'pixel_287_b',
 'pixel_288_r',
 'pixel_288_g',
 'pixel_288_b',
 'pixel_289_r',
 'pixel_289_g',
 'pixel_289_b',
 'pixel_290_r',
 'pixel_290_g',
 'pixel_290_b',
 'pixel_291_r',
 'pixel_291_g',
 'pixel_291_b',
 'pixel_292_r',
 'pixel_292_g',
 'pixel_292_b',
 'pixel_293_r',
 'pixel_293_g',
 'pixel_293_b',
 'pixel_294_r',
 'pixel_294_g',
 'pixel_294_b',
 'pixel_295_r',
 'pixel_295_g',
 'pixel_295_b',
 'pixel_296_r',
 'pixel_296_g',
 'pixel_296_b',
 'pixel_297_r',
 'pixel_297_g',
 'pixel_297_b',
 'pixel_298_r',
 'pixel_298_g',
 'pixel_298_b',
 'pixel_299_r',
 'pixel_299_g',
 'pixel_299_b',
 'pixel_300_r',
 'pixel_300_g',
 'pixel_300_b',
 'pixel_301_r',
 'pixel_301_g',
 'pixel_301_b',
 'pixel_302_r',
 'pixel_302_g',
 'pixel_302_b',
 'pixel_303_r',
 'pixel_303_g',
 'pixel_303_b',
 'pixel_304_r',
 'pixel_304_g',
 'pixel_304_b',
 'pixel_305_r',
 'pixel_305_g',
 'pixel_305_b',
 'pixel_306_r',
 'pixel_306_g',
 'pixel_306_b',
 'pixel_307_r',
 'pixel_307_g',
 'pixel_307_b',
 'pixel_308_r',
 'pixel_308_g',
 'pixel_308_b',
 'pixel_309_r',
 'pixel_309_g',
 'pixel_309_b',
 'pixel_310_r',
 'pixel_310_g',
 'pixel_310_b',
 'pixel_311_r',
 'pixel_311_g',
 'pixel_311_b',
 'pixel_312_r',
 'pixel_312_g',
 'pixel_312_b',
 'pixel_313_r',
 'pixel_313_g',
 'pixel_313_b',
 'pixel_314_r',
 'pixel_314_g',
 'pixel_314_b',
 'pixel_315_r',
 'pixel_315_g',
 'pixel_315_b',
 'pixel_316_r',
 'pixel_316_g',
 'pixel_316_b',
 'pixel_317_r',
 'pixel_317_g',
 'pixel_317_b',
 'pixel_318_r',
 'pixel_318_g',
 'pixel_318_b',
 'pixel_319_r',
 'pixel_319_g',
 'pixel_319_b',
 'pixel_320_r',
 'pixel_320_g',
 'pixel_320_b',
 'pixel_321_r',
 'pixel_321_g',
 'pixel_321_b',
 'pixel_322_r',
 'pixel_322_g',
 'pixel_322_b',
 'pixel_323_r',
 'pixel_323_g',
 'pixel_323_b',
 'pixel_324_r',
 'pixel_324_g',
 'pixel_324_b',
 'pixel_325_r',
 'pixel_325_g',
 'pixel_325_b',
 'pixel_326_r',
 'pixel_326_g',
 'pixel_326_b',
 'pixel_327_r',
 'pixel_327_g',
 'pixel_327_b',
 'pixel_328_r',
 'pixel_328_g',
 'pixel_328_b',
 'pixel_329_r',
 'pixel_329_g',
 'pixel_329_b',
 'pixel_330_r',
 ...]

In [62]:
first_row

['ISIC_0024370_aug_0.jpg',
 '0.0',
 '0.0',
 '0.0',
 '0.0',
 '0.0',
 '0.0',
 '1.0',
 './augmented_images/ISIC_0024370_aug_0.jpg',
 '183',
 '127',
 '136',
 '183',
 '127',
 '136',
 '183',
 '127',
 '136',
 '183',
 '127',
 '136',
 '184',
 '128',
 '137',
 '184',
 '128',
 '137',
 '185',
 '129',
 '138',
 '185',
 '129',
 '138',
 '185',
 '129',
 '138',
 '185',
 '129',
 '138',
 '185',
 '129',
 '138',
 '185',
 '129',
 '138',
 '185',
 '129',
 '138',
 '184',
 '128',
 '137',
 '184',
 '128',
 '137',
 '184',
 '128',
 '137',
 '184',
 '128',
 '137',
 '184',
 '128',
 '137',
 '185',
 '129',
 '138',
 '185',
 '129',
 '138',
 '185',
 '129',
 '138',
 '185',
 '129',
 '138',
 '185',
 '129',
 '138',
 '185',
 '129',
 '138',
 '184',
 '128',
 '137',
 '184',
 '128',
 '137',
 '184',
 '128',
 '137',
 '183',
 '127',
 '137',
 '182',
 '126',
 '138',
 '182',
 '126',
 '139',
 '182',
 '126',
 '139',
 '182',
 '126',
 '139',
 '182',
 '126',
 '139',
 '182',
 '126',
 '139',
 '182',
 '126',
 '139',
 '182',
 '126',
 '139',
 '181',
 '125',
 '138',
 '181',
 '125',
 '138',
 '180',
 '124',
 '137',
 '179',
 '123',
 '136',
 '179',
 '123',
 '136',
 '180',
 '124',
 '137',
 '182',
 '126',
 '139',
 '183',
 '127',
 '140',
 '183',
 '127',
 '140',
 '183',
 '127',
 '140',
 '182',
 '126',
 '139',
 '182',
 '126',
 '139',
 '181',
 '125',
 '138',
 '181',
 '125',
 '138',
 '180',
 '124',
 '137',
 '180',
 '124',
 '137',
 '180',
 '124',
 '137',
 '179',
 '123',
 '136',
 '179',
 '123',
 '135',
 '179',
 '123',
 '134',
 '180',
 '124',
 '135',
 '181',
 '125',
 '135',
 '181',
 '125',
 '134',
 '181',
 '125',
 '134',
 '182',
 '126',
 '135',
 '182',
 '126',
 '135',
 '182',
 '126',
 '135',
 '183',
 '126',
 '135',
 '184',
 '127',
 '136',
 '184',
 '127',
 '136',
 '184',
 '127',
 '136',
 '185',
 '128',
 '137',
 '185',
 '128',
 '137',
 '184',
 '126',
 '136',
 '183',
 '124',
 '133',
 '183',
 '123',
 '133',
 '183',
 '123',
 '133',
 '183',
 '122',
 '133',
 '184',
 '122',
 '133',
 '184',
 '122',
 '133',
 '183',
 '121',
 '132',
 '183',
 '121',
 '132',
 '182',
 '120',
 '131',
 '182',
 '120',
 '131',
 '181',
 '118',
 '130',
 '179',
 '118',
 '129',
 '179',
 '118',
 '129',
 '178',
 '118',
 '128',
 '178',
 '118',
 '126',
 '177',
 '118',
 '126',
 '176',
 '118',
 '126',
 '176',
 '119',
 '126',
 '176',
 '119',
 '126',
 '176',
 '119',
 '126',
 '176',
 '118',
 '126',
 '177',
 '118',
 '126',
 '177',
 '117',
 '125',
 '177',
 '117',
 '125',
 '176',
 '116',
 '124',
 '176',
 '116',
 '124',
 '176',
 '116',
 '124',
 '176',
 '116',
 '124',
 '177',
 '116',
 '124',
 '178',
 '117',
 '125',
 '178',
 '117',
 '125',
 '178',
 '117',
 '125',
 '178',
 '117',
 '125',
 '178',
 '117',
 '125',
 '178',
 '116',
 '124',
 '178',
 '115',
 '124',
 '178',
 '115',
 '124',
 '178',
 '115',
 '124',
 '178',
 '115',
 '124',
 '178',
 '115',
 '124',
 '178',
 '115',
 '124',
 '178',
 '115',
 '124',
 '179',
 '116',
 '127',
 '179',
 '116',
 '127',
 '178',
 '115',
 '126',
 '177',
 '114',
 '125',
 '176',
 '113',
 '124',
 '176',
 '113',
 '124',
 '176',
 '113',
 '124',
 '178',
 '113',
 '124',
 '179',
 '113',
 '125',
 '179',
 '113',
 '125',
 '178',
 '112',
 '123',
 '176',
 '110',
 '120',
 '176',
 '110',
 '120',
 '176',
 '109',
 '119',
 '176',
 '108',
 '119',
 '175',
 '107',
 '118',
 '175',
 '107',
 '118',
 '175',
 '107',
 '118',
 '175',
 '107',
 '118',
 '175',
 '107',
 '118',
 '175',
 '106',
 '117',
 '175',
 '106',
 '116',
 '176',
 '106',
 '116',
 '176',
 '106',
 '116',
 '176',
 '106',
 '116',
 '176',
 '106',
 '116',
 '176',
 '106',
 '116',
 '176',
 '105',
 '117',
 '176',
 '105',
 '118',
 '176',
 '105',
 '119',
 '176',
 '105',
 '120',
 '175',
 '104',
 '120',
 '175',
 '104',
 '120',
 '175',
 '104',
 '120',
 '174',
 '103',
 '119',
 '174',
 '103',
 '119',
 '174',
 '103',
 '119',
 '174',
 '103',
 '119',
 '173',
 '102',
 '118',
 '173',
 '102',
 '118',
 '173',
 '102',
 '118',
 '174',
 '103',
 '119',
 '176',
 '105',
 '121',
 '178',
 '107',
 '123',
 '178',
 '107',
 '123',
 '177',
 '106',
 '122',
 '176',
 '105',
 '121',
 '176',
 '105',
 '121',
 '175',
 '104',
 '120',
 '174',
 '103',
 '119',
 '173',
 '102',
 '118',
 '173',
 '102',
 '118',
 '172',
 '101',
 '117',
 '171',
 '100',
 '116',
 '171',
 '100',
 '116',
 '171',
 '99',
 '116',
 '171',
 '98',
 '116',
 '170',
 '97',
 '116',
 '170',
 '97',
 '116',
 '170',
 '97',
 '116',
 '170',
 '97',
 '116',
 '170',
 '97',
 '116',
 '171',
 '98',
 '117',
 '173',
 '100',
 '119',
 '174',
 '101',
 '120',
 '174',
 '101',
 '120',
 '173',
 '100',
 '119',
 '172',
 '99',
 '118',
 '171',
 '98',
 '117',
 '171',
 '98',
 '117',
 '171',
 '98',
 '117',
 '171',
 '98',
 '117',
 '171',
 '98',
 '117',
 '171',
 '98',
 '117',
 '172',
 '99',
 '118',
 '172',
 '99',
 '118',
 '171',
 '98',
 '117',
 '171',
 '98',
 '117',
 '170',
 '97',
 '116',
 '170',
 '97',
 '116',
 '169',
 '96',
 '115',
 '168',
 '96',
 '114',
 '167',
 '96',
 '114',
 '167',
 '96',
 '114',
 '167',
 '96',
 '115',
 '167',
 '96',
 '116',
 '166',
 '96',
 '116',
 '166',
 '97',
 '116',
 '165',
 '96',
 '115',
 '165',
 '96',
 '115',
 '165',
 '95',
 '114',
 '165',
 '94',
 '114',
 '166',
 '94',
 '114',
 '166',
 '94',
 '114',
 '165',
 '93',
 '113',
 '165',
 '93',
 '113',
 '165',
 '93',
 '113',
 '165',
 '93',
 '113',
 '165',
 '93',
 '113',
 '166',
 '93',
 '113',
 '166',
 '93',
 '113',
 '168',
 '94',
 '115',
 '169',
 '94',
 '115',
 '169',
 '94',
 '115',
 '169',
 '94',
 '115',
 '169',
 '94',
 '115',
 '169',
 '94',
 '115',
 '169',
 '94',
 '115',
 '171',
 '96',
 '117',
 '172',
 '97',
 '118',
 '173',
 '98',
 '119',
 '175',
 '100',
 '121',
 '183',
 '127',
 '136',
 '183',
 '127',
 '136',
 '183',
 '127',
 '136',
 '183',
 '127',
 '136',
 '184',
 '128',
 '137',
 '184',
 '128',
 '137',
 '185',
 '129',
 '138',
 '185',
 '129',
 '138',
 '185',
 '129',
 '138',
 '185',
 '129',
 '138',
 '185',
 '129',
 '138',
 '185',
 '129',
 '138',
 '185',
 '129',
 '138',
 '184',
 '128',
 '137',
 '184',
 '128',
 '137',
 '184',
 '128',
 '137',
 '184',
 '128',
 '137',
 '184',
 '128',
 '137',
 '185',
 '129',
 '138',
 '185',
 '129',
 '138',
 '185',
 '129',
 '138',
 '185',
 '129',
 '138',
 '185',
 '129',
 '138',
 '185',
 '129',
 '138',
 '184',
 '128',
 '137',
 '184',
 '128',
 '137',
 '184',
 '128',
 '137',
 '183',
 '127',
 '137',
 '182',
 '126',
 '138',
 '182',
 '126',
 '138',
 '182',
 '126',
 '139',
 '182',
 '126',
 '139',
 '182',
 '126',
 '139',
 '182',
 '126',
 '139',
 '182',
 '126',
 '139',
 '182',
 '126',
 '139',
 '182',
 '125',
 '139',
 '181',
 '125',
 '138',
 '180',
 '124',
 '137',
 '180',
 '124',
 '137',
 '179',
 '123',
 '136',
 '180',
 '124',
 '137',
 '182',
 '126',
 '139',
 '183',
 '127',
 '140',
 '182',
 '126',
 '139',
 '182',
 '126',
 '139',
 '182',
 '126',
 '139',
 '182',
 '126',
 '139',
 '181',
 '125',
 '138',
 '180',
 '124',
 '137',
 '180',
 '124',
 '137',
 '179',
 '123',
 '136',
 '179',
 '123',
 '136',
 '179',
 '123',
 '136',
 '179',
 '123',
 '134',
 '179',
 '123',
 '133',
 '180',
 '124',
 '134',
 '180',
 '124',
 '134',
 '180',
 '124',
 '133',
 '180',
 '124',
 '133',
 '181',
 '125',
 '134',
 '181',
 '125',
 '134',
 '181',
 '125',
 '134',
 '182',
 '126',
 '135',
 '183',
 '126',
 '135',
 '183',
 '126',
 '135',
 '183',
 '126',
 '135',
 '184',
 '127',
 '136',
 '184',
 '127',
 '136',
 '184',
 '126',
 '135',
 '183',
 '123',
 '133',
 '183',
 '123',
 '133',
 '183',
 '123',
 '133',
 '183',
 '122',
 '133',
 '184',
 '122',
 '133',
 '184',
 '122',
 '133',
 '183',
 '121',
 '132',
 '183',
 '121',
 '132',
 '182',
 '120',
 '131',
 '182',
 '120',
 '131',
 '181',
 '119',
 '130',
 '180',
 '118',
 '129',
 '179',
 '118',
 '129',
 '178',
 '118',
 '128',
 '178',
 '118',
 '126',
 '177',
 '118',
 '126',
 '176',
 '118',
 '126',
 '176',
 '119',
 '126',
 '176',
 '119',
 '126',
 '176',
 '119',
 '126',
 '176',
 '119',
 '126',
 '177',
 '118',
 '126',
 '177',
 '117',
 '125',
 '177',
 '117',
 '125',
 '176',
 '116',
 '124',
 '176',
 '116',
 '124',
 '176',
 '116',
 '124',
 '176',
 '116',
 '124',
 '177',
 '116',
 '124',
 '177',
 '116',
 '124',
 '177',
 '116',
 '124',
 '177',
 '116',
 '124',
 '177',
 '116',
 '124',
 '177',
 '116',
 '124',
 '177',
 '115',
 '124',
 '177',
 '114',
 '123',
 '177',
 ...]

----

In [8]:
#  undersampling fomr top (NV):

input_csv = "./ordered_training_df.csv"
output_csv_base  = "./ordered_training_df"
chunk_size = 1000  
limits = [1500, 3000]

reduced_nv_data = []

In [9]:

def process_and_save_nv_class(file_path, chunk_size=1000, limit= 1500):

    output_nv_file = output_csv_base + f"_upper_limit_{limit}.csv"
    chunk_iter = pd.read_csv(file_path, chunksize=chunk_size)
    first_chunk = True
    nv_samples_added = 0
    print(f"Processing with NV limit = {limit}")
    
    for i, df_chunk in enumerate(chunk_iter):
        print(f"Processing chunk {i}...")

        # Check if NV column exists
        if 'NV' not in df_chunk.columns:
            raise KeyError("'NV' column not found in dataset. Ensure labels are one-hot encoded.")

        df_nv = df_chunk[df_chunk['NV'] == 1]
        df_other_classes = df_chunk[df_chunk['NV'] != 1]  # K

        # Calculate how many NV samples are needed to reach the limit
        remaining_nv_samples = limit - nv_samples_added

        if remaining_nv_samples > 0:
            # Sample only the required amount of NV rows
            df_nv_reduced = df_nv.sample(n=min(len(df_nv), remaining_nv_samples), random_state=42)

            # Update the count of NV samples added
            nv_samples_added += len(df_nv_reduced)
        else:
            # If the limit is reached, no NV samples are added
            df_nv_reduced = pd.DataFrame()

        df_combined = pd.concat([df_nv_reduced, df_other_classes])
        df_combined.to_csv(output_nv_file, mode='a', header=first_chunk, index=False)
        first_chunk = False



for limit in limits:
    process_and_save_nv_class(input_csv, chunk_size, limit)

Processing with NV limit = 1500
Processing chunk 0...
Processing chunk 1...
Processing chunk 2...
Processing chunk 3...
Processing chunk 4...
Processing chunk 5...
Processing chunk 6...
Processing chunk 7...
Processing chunk 8...
Processing chunk 9...
Processing chunk 10...
Processing with NV limit = 3000
Processing chunk 0...
Processing chunk 1...
Processing chunk 2...
Processing chunk 3...
Processing chunk 4...
Processing chunk 5...
Processing chunk 6...
Processing chunk 7...
Processing chunk 8...
Processing chunk 9...
Processing chunk 10...

In [9]:
with open(f"{input_csv}", "r") as f:
    row_count = sum(1 for _ in f) - 1
print(row_count)

10015

In [10]:
limit = 1500
output_nv_file = output_csv_base + f"_upper_limit_{limit}.csv"

with open(f"{output_nv_file}", "r") as f:
    row_count = sum(1 for _ in f) - 1
print(row_count)

4810

In [11]:
limit = 3000
output_nv_file = output_csv_base + f"_upper_limit_{limit}.csv"

with open(f"{output_nv_file}", "r") as f:
    row_count = sum(1 for _ in f) - 1
print(row_count)

6310

In [12]:
limit= 1500
chunk_size = 3
output_nv_file = output_csv_base + f"_upper_limit_{limit}.csv"
chunk_iter = pd.read_csv(output_nv_file, chunksize=chunk_size)
first_chunk = True

for i, df_chunk in enumerate(chunk_iter):
    print(f"Processing chunk {i}...")
    print(df_chunk["NV"])
    break

Processing chunk 0...
0    1.0
1    1.0
2    1.0
Name: NV, dtype: float64

In [13]:
chunk_size = 3
chunk_iter = pd.read_csv(input_csv, chunksize=chunk_size)
first_chunk = True

for i, df_chunk in enumerate(chunk_iter):
    print(f"Processing chunk {i}...")
    print(df_chunk["NV"])
    break

Processing chunk 0...
0    1.0
1    1.0
2    1.0
Name: NV, dtype: float64